import type { BuildingKind } from '../generated/gameBalance.ts';

/**
 * Canonical card artwork for every authoritative building kind. The same
 * identity is reused by build menus and inspectors.
 */
export const BUILDING_CARD_ART = {
  founders_camp: '/assets/ui/build-menu/cards/founders-camp.webp',
  salvage_pile: '/assets/ui/build-menu/cards/village-storehouse.webp',
  lumber_mill: '/assets/ui/build-menu/cards/lumber-mill.webp',
  reforester: '/assets/ui/build-menu/cards/reforester.webp',
  woodcutters_lodge: '/assets/ui/build-menu/cards/woodcutters-lodge.webp',
  stone_quarry: '/assets/ui/build-menu/cards/stonecutters-camp.webp',
  large_quarry: '/assets/ui/build-menu/cards/large-quarry.webp',
  mine: '/assets/ui/build-menu/cards/iron-mine.webp',
  charcoal_burner: '/assets/ui/build-menu/cards/charcoal-burner.webp',
  smithy: '/assets/ui/build-menu/cards/smithy-bloomery.webp',
  potter_kiln: '/assets/ui/build-menu/cards/potter-kiln.webp',
  well: '/assets/ui/build-menu/cards/water-well.webp',
  stable: '/assets/ui/build-menu/cards/stable.webp',
  hunters_hall: '/assets/ui/build-menu/cards/hunter-hall.webp',
  foragers_shed: '/assets/ui/build-menu/cards/foragers-hut.webp',
  fishing_camp: '/assets/ui/build-menu/cards/fishing-camp.webp',
  chapel: '/assets/ui/build-menu/cards/chapel.webp',
  wayside_shrine: '/assets/ui/build-menu/cards/wayside-shrine.webp',
  marketplace: '/assets/ui/build-menu/cards/market.webp',
  trading_post: '/assets/ui/build-menu/cards/trading-post.webp',
  town_hall: '/assets/ui/build-menu/cards/town-hall.webp',
  village_storehouse: '/assets/ui/build-menu/cards/village-storehouse.webp',
  watchtower: '/assets/ui/build-menu/cards/watchtower.webp',
  guardhouse: '/assets/ui/build-menu/cards/guardhouse.webp',
  palisaded_refuge: '/assets/ui/build-menu/cards/palisaded-refuge.webp',
  threshing_barn: '/assets/ui/build-menu/cards/threshing-barn.webp',
  pastoral_farmstead: '/assets/ui/build-menu/cards/pastoral-farmstead.webp',
  swineherd: '/assets/ui/build-menu/cards/swineherd.webp',
  monastery: '/assets/ui/build-menu/cards/monastery.webp',
  brewery: '/assets/ui/build-menu/cards/brewery.webp',
  tavern: '/assets/ui/build-menu/cards/tavern.webp',
  smokehouse: '/assets/ui/build-menu/cards/smokehouse.webp',
  granary: '/assets/ui/build-menu/cards/granary.webp',
  bakery: '/assets/ui/build-menu/cards/bakery.webp',
  apiary: '/assets/ui/build-menu/cards/apiary.webp',
  watermill: '/assets/ui/build-menu/cards/watermill.webp',
  windmill: '/assets/ui/build-menu/cards/windmill.webp',
  carpenter: '/assets/ui/build-menu/cards/carpenter.webp',
  spinning_retting_house: '/assets/ui/build-menu/cards/spinning-retting-house.webp',
  weaver: '/assets/ui/build-menu/cards/weaver.webp',
  tannery: '/assets/ui/build-menu/cards/tannery.webp',
  cobbler: '/assets/ui/build-menu/cards/cobbler.webp',
  chandlery: '/assets/ui/build-menu/cards/chandlery.webp',
} as const satisfies Record<BuildingKind, string>;
