import type { BuildingKind } from '../generated/gameBalance.ts';
import type { PlacementBuildMenuAction } from './buildMenuCards.ts';

export const BUILDING_KIND_TO_MENU_ACTION: Partial<Record<BuildingKind, PlacementBuildMenuAction>> = {
  founders_camp: 'founders-camp',
  salvage_pile: 'village-storehouse',
  lumber_mill: 'lumber-mill',
  reforester: 'reforester',
  stone_quarry: 'stone-quarry',
  large_quarry: 'large-quarry',
  mine: 'mine',
  charcoal_burner: 'charcoal-burner',
  smithy: 'smithy',
  weaponsmith_armorer: 'weaponsmith-armorer',
  bowyer_fletcher: 'bowyer-fletcher',
  potter_kiln: 'potter-kiln',
  woodcutters_lodge: 'woodcutters-lodge',
  well: 'well',
  stable: 'stable',
  kennel: 'kennel',
  hunters_hall: 'hunters-hall',
  foragers_shed: 'foragers-shed',
  fishing_camp: 'fishing-camp',
  chapel: 'chapel',
  wayside_shrine: 'wayside-shrine',
  marketplace: 'marketplace',
  trading_post: 'trading-post',
  town_hall: 'town-hall',
  village_storehouse: 'village-storehouse',
  watchtower: 'watchtower',
  guardhouse: 'guardhouse',
  palisaded_refuge: 'palisaded-refuge',
  threshing_barn: 'threshing-barn',
  monastery: 'monastery',
  brewery: 'brewery',
  tavern: 'tavern',
  smokehouse: 'smokehouse',
  granary: 'granary',
  bakery: 'bakery',
  apiary: 'apiary',
  watermill: 'watermill',
  windmill: 'windmill',
  carpenter: 'carpenter',
  spinning_retting_house: 'spinning-retting-house',
  weaver: 'weaver',
  tannery: 'tannery',
  cobbler: 'cobbler',
  chandlery: 'chandlery',
  pastoral_farmstead: 'pastoral-farmstead',
  swineherd: 'swineherd',
};

export type BuildingMenuAction = Exclude<PlacementBuildMenuAction, 'residences' | 'dry-stone-wall'>;

export const MENU_ACTION_TO_BUILDING_KIND: Record<BuildingMenuAction, BuildingKind> = {
  'founders-camp': 'founders_camp',
  'lumber-mill': 'lumber_mill',
  'reforester': 'reforester',
  'stone-quarry': 'stone_quarry',
  'large-quarry': 'large_quarry',
  mine: 'mine',
  'charcoal-burner': 'charcoal_burner',
  smithy: 'smithy',
  'weaponsmith-armorer': 'weaponsmith_armorer',
  'bowyer-fletcher': 'bowyer_fletcher',
  'potter-kiln': 'potter_kiln',
  'woodcutters-lodge': 'woodcutters_lodge',
  well: 'well',
  stable: 'stable',
  kennel: 'kennel',
  'hunters-hall': 'hunters_hall',
  'foragers-shed': 'foragers_shed',
  'fishing-camp': 'fishing_camp',
  chapel: 'chapel',
  'wayside-shrine': 'wayside_shrine',
  marketplace: 'marketplace',
  'trading-post': 'trading_post',
  'town-hall': 'town_hall',
  'village-storehouse': 'village_storehouse',
  watchtower: 'watchtower',
  guardhouse: 'guardhouse',
  'palisaded-refuge': 'palisaded_refuge',
  'threshing-barn': 'threshing_barn',
  monastery: 'monastery',
  brewery: 'brewery',
  tavern: 'tavern',
  smokehouse: 'smokehouse',
  granary: 'granary',
  bakery: 'bakery',
  apiary: 'apiary',
  watermill: 'watermill',
  windmill: 'windmill',
  carpenter: 'carpenter',
  'spinning-retting-house': 'spinning_retting_house',
  weaver: 'weaver',
  tannery: 'tannery',
  cobbler: 'cobbler',
  chandlery: 'chandlery',
  'pastoral-farmstead': 'pastoral_farmstead',
  swineherd: 'swineherd',
};

export function toolbarModeToMenuAction(
  mode: BuildingKind | 'road' | 'dry-stone-wall' | 'residences' | 'farm-fields' | 'pastures' | 'burial-grounds' | 'vineyards' | 'idle',
): PlacementBuildMenuAction | null {
  if (mode === 'idle' || mode === 'road') return null;
  if (mode === 'dry-stone-wall') return 'dry-stone-wall';
  if (mode === 'residences') return 'residences';
  if (mode === 'vineyards') return null;
  if (mode === 'farm-fields' || mode === 'pastures' || mode === 'burial-grounds') return null;
  return BUILDING_KIND_TO_MENU_ACTION[mode] ?? null;
}
