import { foodSpoilageLabel, type FoodInventoryKind } from '../economy/foodInventory.ts';
import type { ResourceCostKind } from './resourceCost.ts';

/** Resource identities shared by stock cards and inspector hover cards. */
export const RESOURCE_DESCRIPTIONS: Readonly<Record<ResourceCostKind, string>> = {
  timber: 'Felled and sawn wood for buildings, mine supports, carts, and weapons.',
  stone: 'Quarried stone for walls, foundations, and other masonry.',
  ironwork: 'Forged tools and fittings for construction, workshop upkeep, carts, and military equipment.',
  roofTiles: 'Fired clay tiles for durable roofs on homes and other buildings.',
  gold: 'Coin used to pay for construction, trade, wages, and supplies.',
  iron: 'Iron from mineral deposits, forged with charcoal into tools and fittings at a Smithy.',
  clay: 'Clay dug from deposits and fired into pottery or roof tiles at a Potter’s kiln.',
  salt: 'Salt used to preserve meat and fish and to make cheese.',
  charcoal: 'Charred wood for smithies and hearths. An equal stock heats homes twice as long as firewood.',
  pottery: 'Fired clay vessels made at a Potter’s kiln for household use and trade.',
  manure: 'Livestock manure spread on fields to replenish the soil.',
  remedies: 'Medicinal herbs gathered from the wild or grown in gardens to care for sick residents.',
  firewood: 'Split wood for household hearths, ovens, kilns, brewing, and other workshop fires.',
  water: 'Water drawn from wells for households, livestock, workshops, and firefighting.',
  food: 'Provisions for household meals.',
  ryeSheaves: 'Harvested rye stalks awaiting threshing into grain at a Farmstead.',
  oatSheaves: 'Harvested oat stalks awaiting threshing into grain at a Farmstead.',
  barleySheaves: 'Harvested barley stalks awaiting threshing into grain at a Farmstead.',
  maslinSheaves: 'Harvested wheat and rye stalks awaiting threshing into maslin grain at a Farmstead.',
  ryeGrain: 'Rye grain kept for sowing or milled into flour for bread.',
  oatGrain: 'Oats for porridge, sowing, and livestock feed. Pastoral farmsteads prepare them into winter fodder.',
  animalFeed: 'Prepared winter fodder stored locally at livestock holdings.',
  maslinGrain: 'Mixed wheat and rye grain kept for sowing or milled into flour for maslin bread.',
  barley: 'Barley kept for sowing or malted at a Brewhouse for ale.',
  malt: 'Barley germinated and dried at a Brewhouse, ready to brew into ale.',
  ryeFlour: 'Milled rye grain baked into rye bread at a Bakery.',
  maslinFlour: 'Milled wheat and rye grain baked into maslin bread at a Bakery.',
  ale: 'Ale brewed from malted barley at a Brewhouse and served in Taverns.',
  cider: 'Cider made from apples at a Brewhouse and served in Taverns.',
  pearCider: 'Cider made from pears at a Brewhouse and served in Taverns.',
  mead: 'Mead fermented from honey at a Brewhouse and served in Taverns.',
  preservedFood: 'Cured meat, smoked fish, cheese, and fruit preserves kept for meals, winter, and shortages.',
  honey: 'Honey from apiaries, eaten at the table or fermented into mead at a Brewhouse.',
  wax: 'Beeswax from backyard and forest apiaries, made into candles at a Chandlery.',
  candles: 'Beeswax candles made at a Chandlery for household comforts, church services, and trade.',
  wine: 'Wine made from vineyard grapes at a monastery, served to guests or sold for household use.',
  wool: 'Sheep fleece spun into yarn at a Spinning and Retting House.',
  flax: 'Flax grown in fields and retted at a Spinning and Retting House to prepare linen fibre.',
  yarn: 'Spun wool used by Weavers to make clothing.',
  linen: 'Prepared flax fibre used for clothing, armor linings, and bowstrings.',
  cloth: 'Clothing made from wool yarn or linen at a Weaver’s workshop for households and trade.',
  pelts: 'Fur-bearing skins from hunted game, stored in Storehouses and sold through Trading Posts.',
  hides: 'Untanned livestock skins made into leather at a Tannery.',
  leather: 'Tanned hides used for shoes and military equipment.',
  shoes: 'Leather footwear made at a Cobbler’s workshop and supplied to households through Marketplaces.',
  polearms: 'Long-shafted weapons made by Carpenters or Weaponsmiths to equip spear, pike, and mounted companies.',
  sidearms: 'Swords and other close-combat weapons made by Weaponsmiths for infantry and cavalry.',
  shields: 'Shields made by Weaponsmiths to protect infantry and cavalry.',
  bows: 'Bows made by a Bowyer and Fletcher to equip archers and horse archers.',
  crossbows: 'Crossbows made by a Bowyer and Fletcher to equip crossbow companies.',
  paddedArmor: 'Quilted armor made from linen and leather for soldiers.',
  mailArmor: 'Armor of linked iron rings made by an Armorer for heavily equipped infantry and cavalry.',
  ammunition: 'Arrows and bolts made by a Bowyer and Fletcher, spent by archers and crossbowmen in battle.',
  ryeBread: 'Bread baked from rye flour for household meals.',
  maslinBread: 'Bread baked from mixed wheat and rye flour for household meals.',
  meat: 'Fresh meat from hunting and livestock, eaten in meals or cured at a Smokehouse.',
  fish: 'Fresh fish caught at Fishing camps, eaten in meals or smoked for storage.',
  berries: 'Wild raspberries gathered by foragers for household meals.',
  mushrooms: 'Edible woodland mushrooms gathered by foragers for household meals.',
  milk: 'Fresh livestock milk, served with meals or made into cheese.',
  apples: 'Orchard apples eaten fresh or made into apple cider at a Brewhouse.',
  pears: 'Orchard pears eaten fresh or made into pear cider at a Brewhouse.',
  cherries: 'Orchard cherries eaten fresh with household meals.',
  aronia: 'Aronia berries from backyard orchards, eaten fresh or made into jam.',
  rosehips: 'Rosehips from backyard orchards, eaten fresh or made into jam.',
  cabbage: 'Cabbages grown in backyard gardens for household meals.',
  carrots: 'Carrots grown in backyard gardens for household meals.',
  beetroot: 'Beetroot grown in backyard gardens for household meals.',
  eggs: 'Eggs gathered from backyard hens for household meals.',
  grapes: 'Vineyard grapes eaten fresh or made into wine at a monastery.',
  curedMeat: 'Salted and cured meat kept for meals and winter stores.',
  smokedFish: 'Fish preserved with smoke and salt at a Smokehouse.',
  cheese: 'Milk preserved with salt at livestock holdings or a Smokehouse.',
  aroniaJam: 'Aronia berries preserved as jam in backyard orchards.',
  rosehipJam: 'Rosehips preserved as jam in backyard orchards.',
};

export function foodResourceTooltip(kind: FoodInventoryKind): string {
  return `${RESOURCE_DESCRIPTIONS[kind]} ${foodSpoilageLabel(kind)}.`;
}
