export const WATCHTOWER_GALLERY_DECK_CENTER_Y = 6.08;
export const WATCHTOWER_GALLERY_DECK_THICKNESS = 0.34;
export const WATCHTOWER_GALLERY_FLOOR_HEIGHT =
  WATCHTOWER_GALLERY_DECK_CENTER_Y + WATCHTOWER_GALLERY_DECK_THICKNESS * 0.5 + 0.02;
export const WATCHTOWER_GALLERY_RAIL_CENTER_Y = 6.62;
export const WATCHTOWER_GALLERY_RAIL_HEIGHT = 0.74;
export const WATCHTOWER_GALLERY_POST_CENTER_Y = 7.25;
export const WATCHTOWER_GALLERY_POST_HEIGHT = 2.25;
export const WATCHTOWER_GALLERY_TOP_BEAM_Y = 8.2;
export const WATCHTOWER_ROOF_CENTER_Y = 9.7;
export const WATCHTOWER_ROOF_HEIGHT = 2.65;

