// Generated by scripts/generateGameBalance.mts — do not edit.
#![allow(dead_code)]

pub const TICK_MICROS: i64 = 200000;
pub const TICK_DT: f64 = 0.2;
pub const BASE_SPEED_NUMERATOR: u16 = 2;
pub const BASE_SPEED_DENOMINATOR: u16 = 5;

pub const CALENDAR_SECONDS_PER_DAY: f64 = 120.0;
pub const CALENDAR_HOURS_PER_DAY: u32 = 24;
pub const CALENDAR_DAYS_PER_MONTH: u32 = 10;
pub const CALENDAR_MONTHS_PER_YEAR: u32 = 12;
pub const CALENDAR_DAYS_PER_WEEK: u32 = 7;
pub const CALENDAR_SUNDAY_WEEKDAY: u32 = 0;
pub const CALENDAR_START_MONTH: u32 = 3;
pub const CALENDAR_DAY_START_HOUR: u32 = 6;
pub const CALENDAR_DAY_START_OFFSET_SECONDS: f64 = 30.0;
pub const CALENDAR_WORK_START_HOUR: u32 = 6;
pub const CALENDAR_WORK_END_HOUR: u32 = 20;

pub const SPRING_RAIN_CHANCE: f64 = 0.55;
pub const SPRING_RAIN_CROP_GROWTH_MULTIPLIER: f64 = 1.12;
pub const SPRING_RAIN_WELL_REFILL_MULTIPLIER: f64 = 1.3;
pub const SUMMER_DROUGHT_CHANCE: f64 = 0.48;
pub const SUMMER_DROUGHT_DURATION_DAYS: u32 = 4;
pub const DROUGHT_CROP_GROWTH_MULTIPLIER: f64 = 0.45;
pub const DROUGHT_FORAGE_REGROWTH_MULTIPLIER: f64 = 0.35;
pub const DROUGHT_WELL_REFILL_MULTIPLIER: f64 = 0.5;
pub const DROUGHT_FISH_LOSS_FRACTION_PER_DAY: f64 = 0.04;
pub const SPRING_FIREWOOD_DEMAND_MULTIPLIER: f64 = 1.0;
pub const SUMMER_FIREWOOD_DEMAND_MULTIPLIER: f64 = 0.7;
pub const AUTUMN_FIREWOOD_DEMAND_MULTIPLIER: f64 = 1.15;
pub const WINTER_FIREWOOD_DEMAND_MULTIPLIER: f64 = 1.8;
pub const SPRING_PASTURE_CAPACITY_MULTIPLIER: f64 = 1.15;
pub const SUMMER_PASTURE_CAPACITY_MULTIPLIER: f64 = 1.0;
pub const AUTUMN_PASTURE_CAPACITY_MULTIPLIER: f64 = 0.9;
pub const WINTER_PASTURE_CAPACITY_MULTIPLIER: f64 = 0.35;
pub const DROUGHT_PASTURE_CAPACITY_MULTIPLIER: f64 = 0.65;
pub const SPRING_BREEDING_MULTIPLIER: f64 = 1.25;
pub const WINTER_BREEDING_MULTIPLIER: f64 = 0.6;
pub const FRESH_FOOD_SPOILAGE_SPRING_PER_DAY: f64 = 0.004;
pub const FRESH_FOOD_SPOILAGE_SUMMER_PER_DAY: f64 = 0.008;
pub const FRESH_FOOD_SPOILAGE_AUTUMN_PER_DAY: f64 = 0.004;
pub const FRESH_FOOD_SPOILAGE_WINTER_PER_DAY: f64 = 0.002;
pub const FRESH_FOOD_SPOILAGE_DROUGHT_PER_DAY: f64 = 0.018;

pub const FIRE_LIGHTNING_IGNITION_CHANCE_PER_RAIN_DAY: f64 = 0.1;
pub const FIRE_ACCIDENT_IGNITION_CHANCE_PER_STRUCTURE_DAY: f64 = 0.0015;
pub const FIRE_DROUGHT_RISK_MULTIPLIER: f64 = 1.8;
pub const FIRE_RAIN_RISK_MULTIPLIER: f64 = 0.25;
pub const FIRE_SPREAD_RADIUS: f64 = 26.0;
pub const FIRE_SPREAD_CHANCE_PER_SECOND: f64 = 0.012;
pub const FIRE_INITIAL_INTENSITY: f64 = 0.28;
pub const FIRE_INTENSITY_GROWTH_PER_SECOND: f64 = 0.012;
pub const FIRE_RAIN_INTENSITY_DAMPING_PER_SECOND: f64 = 0.004;
pub const FIRE_DAMAGE_PER_INTENSITY_SECOND: f64 = 0.013;
pub const FIRE_BUCKET_WATER: f64 = 3.0;
pub const FIRE_BUCKET_SPEED_MPS: f64 = 2.3;
pub const FIRE_BUCKET_UNLOAD_SECONDS: f64 = 2.4;
pub const FIRE_INTENSITY_REDUCTION_PER_WATER: f64 = 0.11;
pub const FIRE_EXTINGUISH_INTENSITY_THRESHOLD: f64 = 0.3;
pub const FIRE_EXTINGUISH_CHANCE_BASE: f64 = 0.22;
pub const FIRE_EXTINGUISH_CHANCE_PER_WATER: f64 = 0.07;
pub const FIRE_RESOLVED_RETENTION_SECONDS: f64 = 12.0;

pub const STARTING_TIMBER: f64 = 160.0;
pub const STARTING_STONE: f64 = 140.0;
pub const STARTING_GOLD: f64 = 0.0;
pub const STONE_SALVAGE_FRACTION: f64 = 0.92;
pub const TIMBER_SALVAGE_FRACTION: f64 = 0.7;
pub const GOLD_SALVAGE_FRACTION: f64 = 0.65;
pub const ECONOMIC_ACTIVITY_TAX_RATE: f64 = 0.18;
pub const ECONOMIC_ACTIVITY_TAX_RATE_MIN: f64 = 0.0;
pub const ECONOMIC_ACTIVITY_TAX_RATE_MAX: f64 = 0.45;
pub const LOW_TAX_PRODUCTIVITY_BOOST: f64 = 0.28;
pub const HIGH_TAX_PRODUCTIVITY_DRAG: f64 = 0.58;
pub const FOOD_SALE_GOLD_PER_UNIT: f64 = 0.35;
pub const RESIDENCE_TIMBER_COST: f64 = 8.0;
pub const RESIDENCE_STONE_COST: f64 = 12.0;
pub const RESIDENCE_TIER2_TIMBER_COST: f64 = 18.0;
pub const RESIDENCE_TIER2_STONE_COST: f64 = 14.0;
pub const RESIDENCE_TIER2_GOLD_COST: f64 = 8.0;
pub const RESIDENCE_TIER3_TIMBER_COST: f64 = 28.0;
pub const RESIDENCE_TIER3_STONE_COST: f64 = 24.0;
pub const RESIDENCE_TIER3_GOLD_COST: f64 = 22.0;
pub const HOUSEHOLD_MAX_WEALTH: f64 = 200.0;
pub const TOWN_HALL_POPULATION_REQUIRED: u32 = 24;
pub const TOWN_HALL_UNSTAFFED_TAX_COLLECTION_MULTIPLIER: f64 = 0.6;

pub const STARTING_POPULATION: u32 = 5;
pub const POPULATION_PER_RESIDENCE: u32 = 3;
pub const RESIDENCE_POPULATION_NARROW: u32 = 2;
pub const RESIDENCE_POPULATION_WIDE: u32 = 4;
pub const NARROW_PARCEL_FRONTAGE_MAX: f64 = 9.6;
pub const WIDE_PARCEL_FRONTAGE_MIN: f64 = 14.0;
pub const RESIDENCE_FIREWOOD_CAPACITY: f64 = 40.0;
pub const RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC: f64 = 0.02;
pub const RESIDENCE_WATER_CAPACITY: f64 = 24.0;
pub const RESIDENCE_WATER_PER_PERSON_PER_SEC: f64 = 0.012;
pub const RESIDENCE_FOOD_CAPACITY: f64 = 32.0;
pub const RESIDENCE_FOOD_PER_PERSON_PER_SEC: f64 = 0.015;
pub const RESIDENCE_TIER1_CAPACITY: u32 = 3;
pub const RESIDENCE_TIER2_CAPACITY: u32 = 6;
pub const RESIDENCE_TIER3_CAPACITY: u32 = 10;
pub const RESIDENCE_PRESERVED_FOOD_CAPACITY: f64 = 28.0;
pub const RESIDENCE_PRESERVED_FOOD_PER_PERSON_PER_SEC: f64 = 0.004;
pub const RESIDENCE_ALE_CAPACITY: f64 = 20.0;
pub const RESIDENCE_ALE_PER_PERSON_PER_SEC: f64 = 0.0025;
pub const ABANDON_AFTER_DEFICIT_TICKS: u32 = 3600;
pub const RESIDENCE_TIER1_ABANDONMENT_GRACE_MULTIPLIER: f64 = 2.5;
pub const RESIDENCE_TIER2_ABANDONMENT_GRACE_MULTIPLIER: f64 = 1.5;
pub const RESIDENCE_TIER3_ABANDONMENT_GRACE_MULTIPLIER: f64 = 1.0;
pub const RESIDENCE_RECOVERY_FIREWOOD_MIN: f64 = 8.0;
pub const RESIDENCE_RECOVERY_WATER_MIN: f64 = 5.0;
pub const RESIDENCE_RECOVERY_FOOD_MIN: f64 = 6.0;
pub const RESIDENCE_SETTLE_TICKS: u32 = 250;
pub const CHAPEL_SETTLEMENT_TICKS_MULTIPLIER: f64 = 0.7;
pub const CHAPEL_ABANDONMENT_DEFICIT_MULTIPLIER: f64 = 0.7;
pub const CHAPEL_TITHE_GOLD_PER_PERSON_PER_DAY: f64 = 0.08;
pub const CHAPEL_BASE_ATTENDANCE_CHANCE: f64 = 0.55;
pub const CHAPEL_PRIEST_ATTENDANCE_BONUS: f64 = 0.25;
pub const CHAPEL_COMMUNITY_ATTENDANCE_BONUS: f64 = 0.15;
pub const CHAPEL_RECOVERY_STOCK_MULTIPLIER: f64 = 0.65;
pub const CHAPEL_RECOVERY_NEEDS_REQUIRED: u32 = 2;
pub const CHAPEL_COFFER_CAPACITY: f64 = 500.0;
pub const CHAPEL_PRIEST_SALARY_GOLD_PER_DAY: f64 = 2.5;
pub const CHAPEL_UPKEEP_GOLD_PER_DAY: f64 = 0.35;
pub const CHAPEL_UNSTAFFED_UPKEEP_FRACTION: f64 = 0.25;
pub const CHAPEL_CHARITY_GOLD_PER_DAY: f64 = 0.12;
pub const CHAPEL_CHARITY_MIN_COFFER_GOLD: f64 = 120.0;
pub const CHAPEL_AUTO_SWEEP_INTERVAL_TICKS: u64 = 900;
pub const CHAPEL_AUTO_SWEEP_FRACTION: f64 = 0.5;
pub const CHAPEL_COFFER_RESERVE_DEFAULT: f64 = 80.0;
pub const CHAPEL_COFFER_RESERVE_MIN: f64 = 20.0;
pub const CHAPEL_COFFER_RESERVE_MAX: f64 = 200.0;
pub const CHAPEL_SABBATH_OBSERVANCE_ATTENDANCE_BONUS: f64 = 0.12;
pub const CHAPEL_SABBATH_OBSERVANCE_SETTLEMENT_BONUS: f64 = 0.08;
pub const MONASTERY_SETTLEMENT_TICKS_MULTIPLIER: f64 = 0.85;
pub const MONASTERY_ABANDONMENT_DEFICIT_MULTIPLIER: f64 = 0.85;
pub const MONASTERY_RECOVERY_STOCK_MULTIPLIER: f64 = 0.92;
pub const MONASTERY_ATTENDANCE_BONUS: f64 = 0.08;
pub const MONASTERY_MIN_FOOTPRINT_SLOPE: f64 = 1.8;

pub const BUILDING_ROAD_ACCESS_DISTANCE: f64 = 20.0;
pub const BURGAGE_ROAD_FRONTAGE_DISTANCE: f64 = 16.0;
pub const MIN_DELIVERY_TRIP_SEC: f64 = 4.0;
pub const FIREWOOD_DELIVERY_SPEED_MPS: f64 = 0.95;
pub const WATER_DELIVERY_SPEED_MPS: f64 = 1.15;
pub const FOOD_DELIVERY_SPEED_MPS: f64 = 1.25;
pub const FIREWOOD_DELIVERY_UNLOAD_SEC: f64 = 10.0;
pub const WATER_DELIVERY_UNLOAD_SEC: f64 = 5.0;
pub const FOOD_DELIVERY_UNLOAD_SEC: f64 = 6.0;
pub const TIMBER_DELIVERY_SPEED_MPS: f64 = 0.85;
pub const TIMBER_DELIVERY_UNLOAD_SEC: f64 = 8.0;

pub const CONSTRUCTION_MAX_BUILDERS: u32 = 4;
pub const CONSTRUCTION_WORK_PER_WORKER_PER_SEC: f64 = 1.0;
pub const CONSTRUCTION_HAUL_PER_WORKER: f64 = 8.0;
pub const CONSTRUCTION_DELIVERY_SPEED_MPS: f64 = 0.9;
pub const CONSTRUCTION_DELIVERY_UNLOAD_SEC: f64 = 6.0;
pub const CONSTRUCTION_TREASURY_TRANSFER_PER_SEC: f64 = 2.0;

pub const LARGE_QUARRY_MAX_YIELD: f64 = 10000.0;
pub const SMALL_QUARRY_MAX_YIELD: f64 = 4000.0;

pub const LODGE_TIMBER_PER_CYCLE: f64 = 3.0;
pub const LODGE_TIMBER_PER_DELIVERY: f64 = 3.0;
pub const LODGE_FIREWOOD_PER_CYCLE: f64 = 3.0;
pub const LODGE_FIREWOOD_PER_DELIVERY: f64 = 2.0;
pub const STONE_PER_HARVEST: f64 = 2.0;
pub const GAME_ANIMALS_PER_HARVEST: f64 = 1.0;
pub const GAME_PER_HARVEST: f64 = 4.0;
pub const BERRIES_PER_HARVEST: f64 = 3.0;
pub const MUSHROOMS_PER_HARVEST: f64 = 3.0;
pub const FISH_PER_HARVEST: f64 = 3.5;
pub const RICH_FISH_YIELD_MULTIPLIER: f64 = 1.75;
pub const FOOD_PER_DELIVERY: f64 = 2.0;
pub const BERRIES_REGROW_PER_DAY: f64 = 18.0;
pub const MUSHROOMS_REGROW_PER_DAY: f64 = 12.0;
pub const FISH_REPRODUCTION_RATE_PER_DAY: f64 = 0.08;
pub const GAME_REPRODUCTION_RATE_PER_DAY: f64 = 0.12;
pub const GAME_MIN_BREEDING_POPULATION: f64 = 2.0;
pub const GAME_HABITAT_DISRUPTION_RADIUS: f64 = 38.0;
pub const REFORESTER_REGROW_PER_SEC: f64 = 0.014;
pub const WELL_BASE_REFILL_PER_SEC: f64 = 0.42;
pub const WELL_SURGE_CHANCE_PER_TICK: f64 = 0.0022;
pub const WELL_SURGE_AMOUNT_MIN: f64 = 10.0;
pub const WELL_SURGE_AMOUNT_MAX: f64 = 26.0;
pub const WELL_SURGE_COOLDOWN_SEC: f64 = 42.0;
pub const WELL_WATER_PER_DELIVERY: f64 = 3.0;
pub const MILL_WATER_PER_HARVEST: f64 = 0.0;
pub const GRAIN_PER_FIELD_CYCLE: f64 = 4.0;
pub const GRAIN_TRANSFER_PER_TRIP: f64 = 6.0;
pub const WATERMILL_GRAIN_PER_CYCLE: f64 = 3.0;
pub const WATERMILL_WATER_PER_CYCLE: f64 = 0.0;
pub const WATERMILL_FLOUR_PER_CYCLE: f64 = 4.0;
pub const GRANARY_FLOUR_PER_CYCLE: f64 = 3.0;
pub const GRANARY_WATER_PER_CYCLE: f64 = 2.0;
pub const GRANARY_FIREWOOD_PER_CYCLE: f64 = 1.0;
pub const GRANARY_FOOD_PER_CYCLE: f64 = 4.0;
pub const BREWERY_GRAIN_PER_CYCLE: f64 = 3.0;
pub const BREWERY_WATER_PER_CYCLE: f64 = 2.0;
pub const BREWERY_ALE_PER_CYCLE: f64 = 4.0;
pub const SMOKEHOUSE_FOOD_PER_CYCLE: f64 = 3.0;
pub const SMOKEHOUSE_FIREWOOD_PER_CYCLE: f64 = 1.0;
pub const SMOKEHOUSE_PRESERVED_FOOD_PER_CYCLE: f64 = 3.0;
pub const APIARY_HONEY_PER_CYCLE: f64 = 2.0;
pub const APIARY_FOOD_PER_CYCLE: f64 = 1.0;
pub const VINEYARD_WINE_PER_CYCLE: f64 = 3.0;
pub const VINEYARD_FOOD_PER_CYCLE: f64 = 1.0;
pub const MONASTERY_GRAIN_PER_CYCLE: f64 = 2.0;
pub const MONASTERY_FOOD_PER_CYCLE: f64 = 2.0;
pub const MONASTERY_PILGRIMAGE_GOLD_PER_DAY: f64 = 3.5;
pub const MONASTERY_UNLINKED_PRODUCTIVITY: f64 = 0.45;
pub const MONASTERY_COVERAGE_RADIUS: f64 = 520.0;
pub const MONASTERY_TITHE_SHARE_DEFAULT: f64 = 0.3;
pub const MONASTERY_CHARITY_FOOD_PER_DELIVERY: f64 = 4.0;
pub const SPECIALTY_EXPORT_GOLD_PER_HONEY: f64 = 0.8;
pub const SPECIALTY_EXPORT_GOLD_PER_ALE: f64 = 1.15;
pub const SPECIALTY_EXPORT_GOLD_PER_WINE: f64 = 1.6;
pub const FERRY_GOLD_PER_DAY: f64 = 2.25;
pub const CARPENTER_DELIVERY_SPEED_MULTIPLIER: f64 = 1.18;
pub const CARPENTER_TIMBER_COST_MULTIPLIER: f64 = 0.9;
pub const STOREHOUSE_OVERFLOW_THRESHOLD: f64 = 0.65;
pub const STOREHOUSE_HAUL_PER_WORKER: f64 = 24.0;

pub const FARM_MIN_FIELD_AREA: f64 = 48.0;
pub const FARM_OPTIMAL_FIELD_AREA: f64 = 1600.0;
pub const FARM_LARGE_FIELD_EFFICIENCY_EXPONENT: f64 = 0.22;
pub const FARM_LARGE_FIELD_EFFICIENCY_FLOOR: f64 = 0.6;
pub const FARM_MIN_FIELD_EDGE: f64 = 6.0;
pub const FARM_WORK_METERS_PER_WORKER_PER_SEC: f64 = 20.0;
pub const FARM_PLOUGH_WORK_PER_SQUARE_METER: f64 = 1.0;
pub const FARM_SOW_WORK_PER_SQUARE_METER: f64 = 0.55;
pub const FARM_HARVEST_WORK_PER_SQUARE_METER: f64 = 0.8;
pub const FARM_GROWTH_SECONDS: f64 = 6000.0;
pub const FARM_BASE_GRAIN_PER_SQUARE_METER: f64 = 0.08;
pub const FARM_RYE_MOISTURE_IDEAL: f64 = 0.38;
pub const FARM_RYE_MOISTURE_TOLERANCE: f64 = 0.52;
pub const FARM_OATS_MOISTURE_IDEAL: f64 = 0.58;
pub const FARM_OATS_MOISTURE_TOLERANCE: f64 = 0.46;
pub const FARM_RYE_FERTILITY_DRAIN: f64 = 0.08;
pub const FARM_OATS_FERTILITY_DRAIN: f64 = 0.06;
pub const FARM_FALLOW_FERTILITY_RESTORE: f64 = 0.18;
pub const FARM_SLOPE_PENALTY_PER_DEGREE: f64 = 0.025;
pub const FARM_MAX_ACCEPTED_SLOPE_DEGREES: f64 = 18.0;
pub const FARM_FIELD_SALVAGE_FRACTION: f64 = 0.0;

pub const LIVESTOCK_MIN_PASTURE_AREA: f64 = 64.0;
pub const LIVESTOCK_MIN_PASTURE_EDGE: f64 = 6.0;
pub const LIVESTOCK_PASTURE_SALVAGE_FRACTION: f64 = 0.0;
pub const CATTLE_STARTER_HERD: u32 = 3;
pub const CATTLE_MAX_HERD: u32 = 10;
pub const CATTLE_AREA_PER_HEAD: f64 = 190.0;
pub const CATTLE_MAX_SLOPE_DEGREES: f64 = 15.0;
pub const CATTLE_MOISTURE_IDEAL: f64 = 0.58;
pub const CATTLE_MOISTURE_TOLERANCE: f64 = 0.52;
pub const CATTLE_FOOD_PER_CYCLE_PER_HEAD: f64 = 0.72;
pub const CATTLE_PRESERVED_FOOD_PER_CYCLE_PER_HEAD: f64 = 0.18;
pub const CATTLE_GRAIN_PER_UNSUPPORTED_HEAD: f64 = 0.34;
pub const CATTLE_BREEDING_PER_CYCLE: f64 = 0.018;
pub const CATTLE_HEALTH_RECOVERY_PER_CYCLE: f64 = 0.035;
pub const CATTLE_HEALTH_LOSS_PER_CYCLE: f64 = 0.08;
pub const CATTLE_FERTILITY_BONUS: f64 = 0.03;
pub const CATTLE_MAX_FERTILIZED_FIELDS: usize = 2;
pub const CATTLE_PLOUGH_WORK_MULTIPLIER: f64 = 0.78;
pub const SHEEP_STARTER_HERD: u32 = 6;
pub const SHEEP_MAX_HERD: u32 = 18;
pub const SHEEP_AREA_PER_HEAD: f64 = 105.0;
pub const SHEEP_MAX_SLOPE_DEGREES: f64 = 28.0;
pub const SHEEP_MOISTURE_IDEAL: f64 = 0.38;
pub const SHEEP_MOISTURE_TOLERANCE: f64 = 0.72;
pub const SHEEP_FOOD_PER_CYCLE_PER_HEAD: f64 = 0.32;
pub const SHEEP_PRESERVED_FOOD_PER_CYCLE_PER_HEAD: f64 = 0.08;
pub const SHEEP_GRAIN_PER_UNSUPPORTED_HEAD: f64 = 0.18;
pub const SHEEP_WOOL_GOLD_PER_CYCLE_PER_HEAD: f64 = 0.075;
pub const SHEEP_BREEDING_PER_CYCLE: f64 = 0.025;
pub const SHEEP_HEALTH_RECOVERY_PER_CYCLE: f64 = 0.04;
pub const SHEEP_HEALTH_LOSS_PER_CYCLE: f64 = 0.065;
pub const SWINE_STARTER_HERD: u32 = 4;
pub const SWINE_MAX_HERD: u32 = 14;
pub const SWINE_AREA_PER_HEAD: f64 = 120.0;
pub const SWINE_MATURE_TREES_PER_HEAD: f64 = 2.5;
pub const SWINE_FOOD_PER_CYCLE_PER_HEAD: f64 = 0.62;
pub const SWINE_GRAIN_PER_UNSUPPORTED_HEAD: f64 = 0.5;
pub const SWINE_BREEDING_PER_CYCLE: f64 = 0.022;
pub const SWINE_HEALTH_RECOVERY_PER_CYCLE: f64 = 0.03;
pub const SWINE_HEALTH_LOSS_PER_CYCLE: f64 = 0.09;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BuildingSimKind {
    LumberMill,
    Reforester,
    StoneQuarry,
    LargeQuarry,
    WoodcuttersLodge,
    Well,
    HuntersHall,
    ForagersShed,
    FishingCamp,
    ThreshingBarn,
    Monastery,
    Brewery,
    Smokehouse,
    Granary,
    Apiary,
    Watermill,
    Carpenter,
    FerryLanding,
    Vineyard,
    PastoralFarmstead,
    Swineherd,
    VillageStorehouse,
}

#[derive(Clone, Copy, Debug)]
pub struct BuildingDef {
    pub kind: &'static str,
    pub cost_timber: f64,
    pub cost_stone: f64,
    pub storage_timber: f64,
    pub storage_firewood: f64,
    pub storage_stone: f64,
    pub storage_water: f64,
    pub storage_food: f64,
    pub storage_grain: f64,
    pub storage_flour: f64,
    pub storage_ale: f64,
    pub storage_preserved_food: f64,
    pub storage_honey: f64,
    pub storage_wine: f64,
    pub accepts_labor: bool,
    pub max_labor: u32,
    pub work_radius: f64,
    pub action_interval: f64,
    pub pick_radius: f64,
    pub requires_road: bool,
    pub requires_mature_trees: bool,
    pub requires_quarry_stone: bool,
    pub requires_game: bool,
    pub requires_berries: bool,
    pub requires_fish: bool,
    pub requires_water_shore: bool,
    pub requires_hillside: bool,
    pub sim_kind: Option<BuildingSimKind>,
}

const LUMBER_MILL: BuildingDef = BuildingDef {
    kind: "lumber_mill",
    cost_timber: 45.0,
    cost_stone: 15.0,
    storage_timber: 240.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 48.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 210.0,
    action_interval: 9.0,
    pick_radius: 8.0,
    requires_road: true,
    requires_mature_trees: true,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::LumberMill),
};

const REFORESTER: BuildingDef = BuildingDef {
    kind: "reforester",
    cost_timber: 35.0,
    cost_stone: 10.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 1,
    work_radius: 190.0,
    action_interval: 0.0,
    pick_radius: 8.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Reforester),
};

const WOODCUTTERS_LODGE: BuildingDef = BuildingDef {
    kind: "woodcutters_lodge",
    cost_timber: 40.0,
    cost_stone: 12.0,
    storage_timber: 60.0,
    storage_firewood: 120.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 5.0,
    pick_radius: 8.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::WoodcuttersLodge),
};

const STONE_QUARRY: BuildingDef = BuildingDef {
    kind: "stone_quarry",
    cost_timber: 25.0,
    cost_stone: 40.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 180.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 4,
    work_radius: 80.0,
    action_interval: 9.0,
    pick_radius: 10.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: true,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::StoneQuarry),
};

const LARGE_QUARRY: BuildingDef = BuildingDef {
    kind: "large_quarry",
    cost_timber: 90.0,
    cost_stone: 70.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 360.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 6,
    work_radius: 0.0,
    action_interval: 7.0,
    pick_radius: 13.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::LargeQuarry),
};

const WELL: BuildingDef = BuildingDef {
    kind: "well",
    cost_timber: 18.0,
    cost_stone: 22.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 100.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 90.0,
    action_interval: 0.0,
    pick_radius: 6.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Well),
};

const HUNTERS_HALL: BuildingDef = BuildingDef {
    kind: "hunters_hall",
    cost_timber: 38.0,
    cost_stone: 14.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 100.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 68.0,
    action_interval: 8.0,
    pick_radius: 9.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: true,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::HuntersHall),
};

const FORAGERS_SHED: BuildingDef = BuildingDef {
    kind: "foragers_shed",
    cost_timber: 28.0,
    cost_stone: 8.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 80.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 48.0,
    action_interval: 6.0,
    pick_radius: 8.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: true,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::ForagersShed),
};

const FISHING_CAMP: BuildingDef = BuildingDef {
    kind: "fishing_camp",
    cost_timber: 34.0,
    cost_stone: 10.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 120.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 64.0,
    action_interval: 7.0,
    pick_radius: 9.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: true,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::FishingCamp),
};

const CHAPEL: BuildingDef = BuildingDef {
    kind: "chapel",
    cost_timber: 22.0,
    cost_stone: 34.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 1,
    work_radius: 0.0,
    action_interval: 0.0,
    pick_radius: 7.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: None,
};

const MARKETPLACE: BuildingDef = BuildingDef {
    kind: "marketplace",
    cost_timber: 32.0,
    cost_stone: 26.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 48.0,
    storage_food: 96.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 0.0,
    pick_radius: 8.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: None,
};

const TOWN_HALL: BuildingDef = BuildingDef {
    kind: "town_hall",
    cost_timber: 88.0,
    cost_stone: 96.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 1,
    work_radius: 0.0,
    action_interval: 0.0,
    pick_radius: 11.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: None,
};

const VILLAGE_STOREHOUSE: BuildingDef = BuildingDef {
    kind: "village_storehouse",
    cost_timber: 54.0,
    cost_stone: 28.0,
    storage_timber: 360.0,
    storage_firewood: 280.0,
    storage_stone: 360.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 4.0,
    pick_radius: 10.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::VillageStorehouse),
};

const THRESHING_BARN: BuildingDef = BuildingDef {
    kind: "threshing_barn",
    cost_timber: 44.0,
    cost_stone: 16.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 280.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 6,
    work_radius: 150.0,
    action_interval: 6.0,
    pick_radius: 9.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::ThreshingBarn),
};

const PASTORAL_FARMSTEAD: BuildingDef = BuildingDef {
    kind: "pastoral_farmstead",
    cost_timber: 40.0,
    cost_stone: 20.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 120.0,
    storage_grain: 90.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 70.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 110.0,
    action_interval: 10.0,
    pick_radius: 10.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::PastoralFarmstead),
};

const SWINEHERD: BuildingDef = BuildingDef {
    kind: "swineherd",
    cost_timber: 34.0,
    cost_stone: 10.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 150.0,
    storage_grain: 120.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 120.0,
    action_interval: 12.0,
    pick_radius: 9.0,
    requires_road: false,
    requires_mature_trees: true,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Swineherd),
};

const MONASTERY: BuildingDef = BuildingDef {
    kind: "monastery",
    cost_timber: 90.0,
    cost_stone: 150.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 180.0,
    storage_grain: 180.0,
    storage_flour: 0.0,
    storage_ale: 120.0,
    storage_preserved_food: 80.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: false,
    max_labor: 0,
    work_radius: 0.0,
    action_interval: 12.0,
    pick_radius: 15.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: true,
    sim_kind: Some(BuildingSimKind::Monastery),
};

const BREWERY: BuildingDef = BuildingDef {
    kind: "brewery",
    cost_timber: 48.0,
    cost_stone: 36.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 100.0,
    storage_food: 0.0,
    storage_grain: 140.0,
    storage_flour: 0.0,
    storage_ale: 200.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 0.0,
    action_interval: 7.0,
    pick_radius: 9.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Brewery),
};

const SMOKEHOUSE: BuildingDef = BuildingDef {
    kind: "smokehouse",
    cost_timber: 34.0,
    cost_stone: 22.0,
    storage_timber: 0.0,
    storage_firewood: 40.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 120.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 180.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 6.0,
    pick_radius: 8.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Smokehouse),
};

const GRANARY: BuildingDef = BuildingDef {
    kind: "granary",
    cost_timber: 50.0,
    cost_stone: 28.0,
    storage_timber: 0.0,
    storage_firewood: 60.0,
    storage_stone: 0.0,
    storage_water: 120.0,
    storage_food: 340.0,
    storage_grain: 420.0,
    storage_flour: 260.0,
    storage_ale: 0.0,
    storage_preserved_food: 180.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 0.0,
    action_interval: 5.0,
    pick_radius: 9.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Granary),
};

const APIARY: BuildingDef = BuildingDef {
    kind: "apiary",
    cost_timber: 22.0,
    cost_stone: 6.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 40.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 140.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 1,
    work_radius: 0.0,
    action_interval: 18.0,
    pick_radius: 7.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Apiary),
};

const WATERMILL: BuildingDef = BuildingDef {
    kind: "watermill",
    cost_timber: 58.0,
    cost_stone: 42.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 80.0,
    storage_food: 0.0,
    storage_grain: 180.0,
    storage_flour: 260.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 0.0,
    action_interval: 7.0,
    pick_radius: 10.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: true,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Watermill),
};

const CARPENTER: BuildingDef = BuildingDef {
    kind: "carpenter",
    cost_timber: 52.0,
    cost_stone: 20.0,
    storage_timber: 140.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 8.0,
    pick_radius: 9.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Carpenter),
};

const FERRY_LANDING: BuildingDef = BuildingDef {
    kind: "ferry_landing",
    cost_timber: 46.0,
    cost_stone: 18.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 0.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 0.0,
    pick_radius: 9.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: true,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::FerryLanding),
};

const VINEYARD: BuildingDef = BuildingDef {
    kind: "vineyard",
    cost_timber: 26.0,
    cost_stone: 18.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    storage_food: 40.0,
    storage_grain: 0.0,
    storage_flour: 0.0,
    storage_ale: 0.0,
    storage_preserved_food: 0.0,
    storage_honey: 0.0,
    storage_wine: 180.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 20.0,
    pick_radius: 11.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    requires_game: false,
    requires_berries: false,
    requires_fish: false,
    requires_water_shore: false,
    requires_hillside: false,
    sim_kind: Some(BuildingSimKind::Vineyard),
};

const ALL: &[BuildingDef] = &[LUMBER_MILL, REFORESTER, WOODCUTTERS_LODGE, STONE_QUARRY, LARGE_QUARRY, WELL, HUNTERS_HALL, FORAGERS_SHED, FISHING_CAMP, CHAPEL, MARKETPLACE, TOWN_HALL, VILLAGE_STOREHOUSE, THRESHING_BARN, PASTORAL_FARMSTEAD, SWINEHERD, MONASTERY, BREWERY, SMOKEHOUSE, GRANARY, APIARY, WATERMILL, CARPENTER, FERRY_LANDING, VINEYARD];

pub fn building_def(kind: &str) -> Option<&'static BuildingDef> {
    ALL.iter().find(|def| def.kind == kind)
}

pub fn building_def_or_err(kind: &str) -> Result<&'static BuildingDef, String> {
    building_def(kind).ok_or_else(|| format!("Unknown building kind: {kind}"))
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum BackyardGardenKind {
    AppleOrchard = 1,
    CherryOrchard = 2,
    VegetableGarden = 3,
    FlowerGarden = 4,
    HerbGarden = 5,
    HenYard = 6,
}

impl BackyardGardenKind {
    pub fn from_id(id: u8) -> Option<Self> {
        match id {
            1 => Some(Self::AppleOrchard),
            2 => Some(Self::CherryOrchard),
            3 => Some(Self::VegetableGarden),
            4 => Some(Self::FlowerGarden),
            5 => Some(Self::HerbGarden),
            6 => Some(Self::HenYard),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct BackyardGardenDef {
    pub kind: BackyardGardenKind,
    pub slug: &'static str,
    #[allow(dead_code)]
    pub label: &'static str,
    pub cost_timber: f64,
    pub cost_stone: f64,
    pub food_self_share: f64,
    pub food_per_person_per_sec: f64,
    pub gold_per_person_per_sec: f64,
}

const BACKYARD_APPLE_ORCHARD: BackyardGardenDef = BackyardGardenDef {
    kind: BackyardGardenKind::AppleOrchard,
    slug: "apple_orchard",
    label: "Apple orchard",
    cost_timber: 10.0,
    cost_stone: 4.0,
    food_self_share: 0.55,
    food_per_person_per_sec: 0.009,
    gold_per_person_per_sec: 0.008,
};

const BACKYARD_CHERRY_ORCHARD: BackyardGardenDef = BackyardGardenDef {
    kind: BackyardGardenKind::CherryOrchard,
    slug: "cherry_orchard",
    label: "Cherry orchard",
    cost_timber: 9.0,
    cost_stone: 3.0,
    food_self_share: 0.5,
    food_per_person_per_sec: 0.008,
    gold_per_person_per_sec: 0.01,
};

const BACKYARD_VEGETABLE_GARDEN: BackyardGardenDef = BackyardGardenDef {
    kind: BackyardGardenKind::VegetableGarden,
    slug: "vegetable_garden",
    label: "Vegetable garden",
    cost_timber: 5.0,
    cost_stone: 2.0,
    food_self_share: 0.65,
    food_per_person_per_sec: 0.012,
    gold_per_person_per_sec: 0.006,
};

const BACKYARD_FLOWER_GARDEN: BackyardGardenDef = BackyardGardenDef {
    kind: BackyardGardenKind::FlowerGarden,
    slug: "flower_garden",
    label: "Flower garden",
    cost_timber: 4.0,
    cost_stone: 1.0,
    food_self_share: 0.0,
    food_per_person_per_sec: 0.0,
    gold_per_person_per_sec: 0.018,
};

const BACKYARD_HERB_GARDEN: BackyardGardenDef = BackyardGardenDef {
    kind: BackyardGardenKind::HerbGarden,
    slug: "herb_garden",
    label: "Herb garden",
    cost_timber: 4.0,
    cost_stone: 2.0,
    food_self_share: 0.0,
    food_per_person_per_sec: 0.0,
    gold_per_person_per_sec: 0.015,
};

const BACKYARD_HEN_YARD: BackyardGardenDef = BackyardGardenDef {
    kind: BackyardGardenKind::HenYard,
    slug: "hen_yard",
    label: "Hen yard",
    cost_timber: 6.0,
    cost_stone: 1.0,
    food_self_share: 0.82,
    food_per_person_per_sec: 0.0105,
    gold_per_person_per_sec: 0.002,
};

const ALL_BACKYARD_GARDENS: &[BackyardGardenDef] = &[BACKYARD_APPLE_ORCHARD, BACKYARD_CHERRY_ORCHARD, BACKYARD_VEGETABLE_GARDEN, BACKYARD_FLOWER_GARDEN, BACKYARD_HERB_GARDEN, BACKYARD_HEN_YARD];

pub fn backyard_garden_def(kind: BackyardGardenKind) -> &'static BackyardGardenDef {
    ALL_BACKYARD_GARDENS
        .iter()
        .find(|def| def.kind == kind)
        .expect("missing backyard garden def")
}

pub fn backyard_garden_def_by_slug(slug: &str) -> Option<&'static BackyardGardenDef> {
    ALL_BACKYARD_GARDENS.iter().find(|def| def.slug == slug)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TradeResource {
    Timber,
    Stone,
    Firewood,
    Food,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TradeResourceSpendScope {
    Aggregate,
    #[allow(dead_code)]
    Treasury,
}

impl TradeResource {
    pub fn spend_scope(self) -> TradeResourceSpendScope {
        match self {
            Self::Timber => TradeResourceSpendScope::Aggregate,
            Self::Stone => TradeResourceSpendScope::Aggregate,
            Self::Firewood => TradeResourceSpendScope::Aggregate,
            Self::Food => TradeResourceSpendScope::Aggregate,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub enum MarketplaceTradeKind {
    GoldBuy { resource: TradeResource, amount: f64, gold_cost: f64 },
    GoldSell { resource: TradeResource, amount: f64, gold_yield: f64 },
    Barter {
        give: TradeResource,
        give_amount: f64,
        receive: TradeResource,
        receive_amount: f64,
    },
}

#[derive(Clone, Copy, Debug)]
pub struct MarketplaceTradeOffer {
    pub id: &'static str,
    pub kind: MarketplaceTradeKind,
}

const TRADE_BUY_TIMBER: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "buy_timber",
    kind: MarketplaceTradeKind::GoldBuy {
        resource: TradeResource::Timber,
        amount: 10.0,
        gold_cost: 16.0,
    },
};

const TRADE_SELL_TIMBER: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "sell_timber",
    kind: MarketplaceTradeKind::GoldSell {
        resource: TradeResource::Timber,
        amount: 10.0,
        gold_yield: 10.0,
    },
};

const TRADE_BUY_STONE: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "buy_stone",
    kind: MarketplaceTradeKind::GoldBuy {
        resource: TradeResource::Stone,
        amount: 10.0,
        gold_cost: 22.0,
    },
};

const TRADE_SELL_STONE: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "sell_stone",
    kind: MarketplaceTradeKind::GoldSell {
        resource: TradeResource::Stone,
        amount: 10.0,
        gold_yield: 14.0,
    },
};

const TRADE_BUY_FIREWOOD: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "buy_firewood",
    kind: MarketplaceTradeKind::GoldBuy {
        resource: TradeResource::Firewood,
        amount: 10.0,
        gold_cost: 8.0,
    },
};

const TRADE_SELL_FIREWOOD: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "sell_firewood",
    kind: MarketplaceTradeKind::GoldSell {
        resource: TradeResource::Firewood,
        amount: 10.0,
        gold_yield: 5.0,
    },
};

const TRADE_SELL_FOOD: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "sell_food",
    kind: MarketplaceTradeKind::GoldSell {
        resource: TradeResource::Food,
        amount: 10.0,
        gold_yield: 8.0,
    },
};

const TRADE_TIMBER_FOR_STONE: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "timber_for_stone",
    kind: MarketplaceTradeKind::Barter {
        give: TradeResource::Timber,
        give_amount: 25.0,
        receive: TradeResource::Stone,
        receive_amount: 10.0,
    },
};

const TRADE_STONE_FOR_TIMBER: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "stone_for_timber",
    kind: MarketplaceTradeKind::Barter {
        give: TradeResource::Stone,
        give_amount: 10.0,
        receive: TradeResource::Timber,
        receive_amount: 20.0,
    },
};

const TRADE_TIMBER_FOR_FIREWOOD: MarketplaceTradeOffer = MarketplaceTradeOffer {
    id: "timber_for_firewood",
    kind: MarketplaceTradeKind::Barter {
        give: TradeResource::Timber,
        give_amount: 10.0,
        receive: TradeResource::Firewood,
        receive_amount: 18.0,
    },
};

const ALL_MARKETPLACE_TRADES: &[MarketplaceTradeOffer] = &[TRADE_BUY_TIMBER, TRADE_SELL_TIMBER, TRADE_BUY_STONE, TRADE_SELL_STONE, TRADE_BUY_FIREWOOD, TRADE_SELL_FIREWOOD, TRADE_SELL_FOOD, TRADE_TIMBER_FOR_STONE, TRADE_STONE_FOR_TIMBER, TRADE_TIMBER_FOR_FIREWOOD];

pub fn marketplace_trade_offer(id: &str) -> Option<&'static MarketplaceTradeOffer> {
    ALL_MARKETPLACE_TRADES.iter().find(|offer| offer.id == id)
}

pub const MARKET_PRICE_UPDATE_INTERVAL_TICKS: u64 = 150;
pub const MARKET_PRICE_MULTIPLIER_MIN: f64 = 0.78;
pub const MARKET_PRICE_MULTIPLIER_MAX: f64 = 1.38;
pub const MARKET_REGIONAL_INDEX_DRIFT: f64 = 0.014;
pub const MARKET_LOCAL_FOOD_DEMAND_WEIGHT: f64 = 0.32;
pub const MARKET_CARAVAN_DELIVERY_WORKERS: u32 = 1;
pub const MARKET_CARAVAN_LABOR_PER_WORKER: u32 = 1;
pub const MARKET_CARAVAN_FOOD_PER_DELIVERY: f64 = 4.0;
pub const MARKET_CARAVAN_WATER_PER_DELIVERY: f64 = 3.0;
pub const HOUSEHOLD_AUTO_BUY_RUNWAY_DAYS: f64 = 0.75;
pub const HOUSEHOLD_AUTO_BUY_COOLDOWN_TICKS: u64 = 450;
pub const CHAPEL_CHARITY_WEALTH_FRACTION: f64 = 0.4;
pub const CHAPEL_CHARITY_RELIEF_FRACTION: f64 = 0.6;

#[derive(Clone, Copy, Debug)]
pub struct MarketCommodityOffer {
    pub id: &'static str,
    pub label: &'static str,
    pub origin: &'static str,
    pub description: &'static str,
    pub food_amount: f64,
    pub base_gold_cost: f64,
}

const COMMODITY_BUY_PORK: MarketCommodityOffer = MarketCommodityOffer {
    id: "buy_pork",
    label: "Smoked pork",
    origin: "Kvarner lowlands",
    description: "Salt-cured pork — staple provender for hungry households",
    food_amount: 8.0,
    base_gold_cost: 10.0,
};

const COMMODITY_BUY_LAMB: MarketCommodityOffer = MarketCommodityOffer {
    id: "buy_lamb",
    label: "Highland lamb",
    origin: "Mountain pastures",
    description: "Pastured lamb from the highland flocks — a regional specialty",
    food_amount: 6.0,
    base_gold_cost: 13.0,
};

const COMMODITY_BUY_VEAL: MarketCommodityOffer = MarketCommodityOffer {
    id: "buy_veal",
    label: "Istrian veal",
    origin: "Coastal caravans",
    description: "Tender veal from Istrian herds — premium but nourishing",
    food_amount: 5.0,
    base_gold_cost: 15.0,
};

const COMMODITY_BUY_KOBASICA: MarketCommodityOffer = MarketCommodityOffer {
    id: "buy_kobasica",
    label: "Dried sausage",
    origin: "Lika smokehouses",
    description: "Smoked kobasica — keeps well on the road",
    food_amount: 4.0,
    base_gold_cost: 8.0,
};

const COMMODITY_BUY_CHEESE: MarketCommodityOffer = MarketCommodityOffer {
    id: "buy_cheese",
    label: "Mountain cheese",
    origin: "Highland dairies",
    description: "Hard sheep's cheese from upland dairies",
    food_amount: 3.0,
    base_gold_cost: 7.0,
};

const ALL_MARKET_COMMODITIES: &[MarketCommodityOffer] = &[COMMODITY_BUY_PORK, COMMODITY_BUY_LAMB, COMMODITY_BUY_VEAL, COMMODITY_BUY_KOBASICA, COMMODITY_BUY_CHEESE];

pub fn all_market_food_commodities() -> &'static [MarketCommodityOffer] {
    ALL_MARKET_COMMODITIES
}

pub fn market_commodity_offer(id: &str) -> Option<&'static MarketCommodityOffer> {
    ALL_MARKET_COMMODITIES.iter().find(|offer| offer.id == id)
}

#[derive(Clone, Copy, Debug)]
pub struct MarketWaterCommodityOffer {
    pub id: &'static str,
    pub label: &'static str,
    pub origin: &'static str,
    pub description: &'static str,
    pub water_amount: f64,
    pub base_gold_cost: f64,
}

const WATER_COMMODITY_BUY_WATER_CASK: MarketWaterCommodityOffer = MarketWaterCommodityOffer {
    id: "buy_water_cask",
    label: "Water cask",
    origin: "Plitvice springs",
    description: "Oak casks of spring water from the karst highlands",
    water_amount: 6.0,
    base_gold_cost: 5.0,
};

const WATER_COMMODITY_BUY_WATER_BARREL: MarketWaterCommodityOffer = MarketWaterCommodityOffer {
    id: "buy_water_barrel",
    label: "Spring water barrel",
    origin: "Highland wells",
    description: "Barrelled well water hauled by mule train",
    water_amount: 10.0,
    base_gold_cost: 8.0,
};

const ALL_MARKET_WATER_COMMODITIES: &[MarketWaterCommodityOffer] = &[WATER_COMMODITY_BUY_WATER_CASK, WATER_COMMODITY_BUY_WATER_BARREL];

pub fn all_market_water_commodities() -> &'static [MarketWaterCommodityOffer] {
    ALL_MARKET_WATER_COMMODITIES
}

pub fn market_water_commodity_offer(id: &str) -> Option<&'static MarketWaterCommodityOffer> {
    ALL_MARKET_WATER_COMMODITIES.iter().find(|offer| offer.id == id)
}
