//! World seed and re-exports from generated balance data.

pub use crate::balance_generated::{
    ABANDON_AFTER_DEFICIT_TICKS, BERRIES_PER_HARVEST, BERRIES_RESPAWN_RADIUS, BERRIES_RESPAWN_SEC,
    BUILDING_ROAD_ACCESS_DISTANCE, BURGAGE_ROAD_FRONTAGE_DISTANCE, FOOD_DELIVERY_SPEED_MPS,
    FOOD_DELIVERY_UNLOAD_SEC, FOOD_PER_DELIVERY, FIREWOOD_DELIVERY_SPEED_MPS,
    FIREWOOD_DELIVERY_UNLOAD_SEC, GAME_PER_HARVEST, GAME_RESPAWN_SEC, LODGE_FIREWOOD_PER_CYCLE,
    LODGE_FIREWOOD_PER_DELIVERY, LODGE_TIMBER_PER_CYCLE, MIN_DELIVERY_TRIP_SEC, MILL_WATER_PER_HARVEST,
    NARROW_PARCEL_FRONTAGE_MAX, POPULATION_PER_RESIDENCE, REFORESTER_REGROW_PER_SEC,
    RESIDENCE_FIREWOOD_CAPACITY, RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC, RESIDENCE_FOOD_CAPACITY,
    RESIDENCE_FOOD_PER_PERSON_PER_SEC, RESIDENCE_POPULATION_NARROW, RESIDENCE_POPULATION_WIDE,
    RESIDENCE_RECOVERY_FIREWOOD_MIN, RESIDENCE_RECOVERY_FOOD_MIN, RESIDENCE_RECOVERY_WATER_MIN,
    RESIDENCE_SETTLE_TICKS, RESIDENCE_WATER_CAPACITY, RESIDENCE_WATER_PER_PERSON_PER_SEC,
    STONE_PER_HARVEST, TICK_DT, TICK_MICROS, WATER_DELIVERY_SPEED_MPS, WATER_DELIVERY_UNLOAD_SEC,
    WELL_BASE_REFILL_PER_SEC, WELL_SURGE_AMOUNT_MAX, WELL_SURGE_AMOUNT_MIN, WELL_SURGE_CHANCE_PER_TICK,
    WELL_SURGE_COOLDOWN_SEC, WELL_WATER_PER_DELIVERY, STARTING_POPULATION, WIDE_PARCEL_FRONTAGE_MIN,
};

pub const DEFAULT_WORLD_SEED: u64 = 0x71a2e0d;
