//! World seed and re-exports from generated balance data.

pub use crate::balance_generated::{
    BERRIES_PER_HARVEST, BUILDING_ROAD_ACCESS_DISTANCE, FISH_PER_HARVEST, GAME_ANIMALS_PER_HARVEST,
    GAME_PER_HARVEST, LODGE_FIREWOOD_PER_CYCLE, LODGE_TIMBER_PER_CYCLE, LODGE_TIMBER_PER_DELIVERY,
    MILL_WATER_PER_HARVEST, MUSHROOMS_PER_HARVEST, NARROW_PARCEL_FRONTAGE_MAX,
    POPULATION_PER_RESIDENCE, REFORESTER_REGROW_PER_SEC, RESIDENCE_FIREWOOD_CAPACITY,
    RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC, RESIDENCE_FOOD_CAPACITY,
    RESIDENCE_FOOD_PER_PERSON_PER_SEC, RESIDENCE_POPULATION_NARROW, RESIDENCE_POPULATION_WIDE,
    RESIDENCE_WATER_CAPACITY, RESIDENCE_WATER_PER_PERSON_PER_SEC, RESIDENCE_WATER_REORDER_FRACTION,
    STARTING_POPULATION, STONE_PER_HARVEST, TICK_DT, TICK_MICROS,
    TIMBER_DELIVERY_SPEED_MPS, TIMBER_DELIVERY_UNLOAD_SEC, WATER_DELIVERY_SPEED_MPS,
    WATER_DELIVERY_UNLOAD_SEC, WELL_SURGE_AMOUNT_MAX, WELL_SURGE_AMOUNT_MIN,
    WELL_SURGE_CHANCE_PER_TICK, WELL_SURGE_COOLDOWN_SEC, WELL_WATER_PER_DELIVERY,
    WIDE_PARCEL_FRONTAGE_MIN,
};

pub const DEFAULT_WORLD_SEED: u64 = 0x71a2e0d;
