//! Medieval Road System — SpacetimeDB server module.
//! Single-player localhost: anonymous identity per browser token; resources/buildings/roads scoped by owner.

mod backyard_garden_policy;
mod balance_generated;
mod building_defs;
mod burgage;
mod constants;
mod construction_priority;
mod db;
mod economy;
mod farming;
mod fire_policy;
mod fire_recovery_policy;
mod foraging_policy;
mod frontier_economy_policy;
mod granary_policy;
mod harvest_reserve_policy;
mod hydrology;
mod hydrology_grid_generated;
mod labor_steward_policy;
mod lifecycle;
mod livestock_policy;
mod marketplace_procurement_policy;
mod monastery_hospitality_policy;
mod placement_validation;
mod processor_labor_policy;
mod processor_output_policy;
mod quarry_balance;
mod reducers;
mod residence_settlement_policy;
mod roads;
mod schedule;
mod season_policy;
mod seasonal_labor_policy;
mod security_policy;
mod simulation;
mod specialty_trade_policy;
mod storehouse_policy;
mod supply_policy;
mod tables;
mod types;
mod well_policy;
mod woodcutter_policy;
mod worksite_stall_policy;
mod world_entities;
mod world_gen;
mod year_round_labor_policy;

pub use constants::DEFAULT_WORLD_SEED;
