//! Persistent-home consequences for sustained unmet household needs.
//!
//! A shortage never deletes a household slot or marks a home abandoned.
//! Instead it first appears as an approval warning, then blocks residence
//! promotion. Household work and survival distribution continue normally.
//! Sustained tier-four non-vital shortages modestly reduce optional local
//! purchases and the sales-tax receipts generated by those purchases.

use crate::balance_generated::{
    CALENDAR_SECONDS_PER_DAY, HOUSEHOLD_TIER4_SHORTAGE_DISCRETIONARY_MULTIPLIER,
    RESIDENCE_SERVICE_WARNING_DAYS, RESIDENCE_UPGRADE_SERVICE_BLOCK_DAYS, TICK_DT,
};

fn ticks_for_days(days: f64) -> u32 {
    ((days.max(0.0) * CALENDAR_SECONDS_PER_DAY / TICK_DT).round() as u64).min(u64::from(u32::MAX))
        as u32
}

pub fn service_shortage_warns(deficit_ticks: u32) -> bool {
    deficit_ticks >= ticks_for_days(RESIDENCE_SERVICE_WARNING_DAYS)
}

pub fn service_shortage_blocks_upgrade(deficit_ticks: u32) -> bool {
    deficit_ticks >= ticks_for_days(RESIDENCE_UPGRADE_SERVICE_BLOCK_DAYS)
}

pub fn tier_four_non_vital_discretionary_multiplier(
    residence_tier: u8,
    non_vital_deficit_ticks: u32,
) -> f64 {
    if residence_tier < 4 || !service_shortage_warns(non_vital_deficit_ticks) {
        return 1.0;
    }
    HOUSEHOLD_TIER4_SHORTAGE_DISCRETIONARY_MULTIPLIER.clamp(0.0, 1.0)
}

pub fn required_chapel_tier(residence_tier: u8) -> u8 {
    if residence_tier >= 4 {
        3
    } else if residence_tier >= 3 {
        2
    } else {
        1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sustained_shortages_escalate_without_removing_housing() {
        let warning = ticks_for_days(RESIDENCE_SERVICE_WARNING_DAYS);
        let blocked = ticks_for_days(RESIDENCE_UPGRADE_SERVICE_BLOCK_DAYS);

        assert!(!service_shortage_warns(warning.saturating_sub(1)));
        assert!(service_shortage_warns(warning));
        assert!(!service_shortage_blocks_upgrade(blocked.saturating_sub(1)));
        assert!(service_shortage_blocks_upgrade(blocked));
    }

    #[test]
    fn church_standard_scales_with_residence_tier() {
        assert_eq!(required_chapel_tier(1), 1);
        assert_eq!(required_chapel_tier(2), 1);
        assert_eq!(required_chapel_tier(3), 2);
        assert_eq!(required_chapel_tier(4), 3);
    }

    #[test]
    fn only_sustained_tier_four_status_shortages_reduce_optional_spending() {
        let warning = ticks_for_days(RESIDENCE_SERVICE_WARNING_DAYS);
        assert_eq!(tier_four_non_vital_discretionary_multiplier(3, warning), 1.0);
        assert_eq!(tier_four_non_vital_discretionary_multiplier(4, warning - 1), 1.0);
        assert_eq!(
            tier_four_non_vital_discretionary_multiplier(4, warning),
            HOUSEHOLD_TIER4_SHORTAGE_DISCRETIONARY_MULTIPLIER,
        );
    }
}
