//! Persistent-home consequences for sustained unmet household needs.
//!
//! A shortage never deletes a household slot or marks a home abandoned.
//! Instead it first appears as an approval warning, then blocks residence
//! promotion. Household work and survival distribution continue normally.
//! Sustained tier-four non-vital shortages modestly reduce optional local
//! purchases and the sales-tax receipts generated by those purchases.

use crate::balance_generated::{
    CALENDAR_HOURS_PER_DAY, CALENDAR_SECONDS_PER_DAY, CALENDAR_WORK_END_HOUR,
    CALENDAR_WORK_START_HOUR, HOUSEHOLD_TIER4_SHORTAGE_DISCRETIONARY_MULTIPLIER,
    RESIDENCE_SERVICE_WARNING_DAYS, RESIDENCE_UPGRADE_SERVICE_BLOCK_DAYS, TICK_DT,
};
use crate::simulation::residence_needs::ResidenceNeedKind;

pub fn daytime_service_ticks_per_day() -> u32 {
    let workday_seconds = CALENDAR_SECONDS_PER_DAY
        * f64::from(CALENDAR_WORK_END_HOUR.saturating_sub(CALENDAR_WORK_START_HOUR))
        / f64::from(CALENDAR_HOURS_PER_DAY.max(1));
    ticks_for_active_seconds(workday_seconds)
}

pub fn service_ticks_per_day(kind: ResidenceNeedKind) -> u32 {
    if kind == ResidenceNeedKind::Firewood {
        ticks_for_active_seconds(CALENDAR_SECONDS_PER_DAY)
    } else {
        daytime_service_ticks_per_day()
    }
}

pub fn service_deficit_days(kind: ResidenceNeedKind, deficit_ticks: u32) -> f64 {
    f64::from(deficit_ticks) / f64::from(service_ticks_per_day(kind).max(1))
}

pub fn service_shortage_warns(kind: ResidenceNeedKind, deficit_ticks: u32) -> bool {
    service_deficit_days(kind, deficit_ticks) + 1e-9 >= RESIDENCE_SERVICE_WARNING_DAYS
}

pub fn service_shortage_blocks_upgrade(kind: ResidenceNeedKind, deficit_ticks: u32) -> bool {
    service_deficit_days(kind, deficit_ticks) + 1e-9
        >= RESIDENCE_UPGRADE_SERVICE_BLOCK_DAYS
}

/// Physical heating continues through ordinary nights; all other needs use
/// the daytime household-service cadence. Protected holy days freeze both
/// clocks so the promised grace window does not expire while all ordinary
/// household activity is suspended.
pub fn service_need_clock_active(
    kind: ResidenceNeedKind,
    is_work_hours: bool,
    protected_holiday: bool,
) -> bool {
    !protected_holiday && (kind == ResidenceNeedKind::Firewood || is_work_hours)
}

pub fn tier_four_non_vital_discretionary_multiplier(
    residence_tier: u8,
    non_vital_deficit_ticks: u32,
) -> f64 {
    if residence_tier < 4
        || !service_shortage_warns(ResidenceNeedKind::Church, non_vital_deficit_ticks)
    {
        return 1.0;
    }
    HOUSEHOLD_TIER4_SHORTAGE_DISCRETIONARY_MULTIPLIER.clamp(0.0, 1.0)
}

fn ticks_for_active_seconds(seconds: f64) -> u32 {
    ((seconds.max(0.0) / TICK_DT).round() as u64).min(u64::from(u32::MAX)) as u32
}

pub fn scale_discretionary_limits(
    spendable: f64,
    unit_limit: f64,
    spending_multiplier: f64,
) -> (f64, f64) {
    let multiplier = spending_multiplier.clamp(0.0, 1.0);
    (
        spendable.max(0.0) * multiplier,
        unit_limit.max(0.0) * multiplier,
    )
}

pub fn required_chapel_tier(residence_tier: u8) -> u8 {
    if residence_tier >= 4 {
        3
    } else if residence_tier >= 3 {
        2
    } else {
        1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn daytime_church_shortage_reaches_the_exact_three_and_six_day_gates() {
        assert_eq!(daytime_service_ticks_per_day(), 350);
        let warning = daytime_service_ticks_per_day() * RESIDENCE_SERVICE_WARNING_DAYS as u32;
        let blocked =
            daytime_service_ticks_per_day() * RESIDENCE_UPGRADE_SERVICE_BLOCK_DAYS as u32;

        assert!(!service_shortage_warns(
            ResidenceNeedKind::Church,
            warning.saturating_sub(1)
        ));
        assert!(service_shortage_warns(
            ResidenceNeedKind::Church,
            warning
        ));
        assert!(!service_shortage_blocks_upgrade(
            ResidenceNeedKind::Church,
            blocked.saturating_sub(1)
        ));
        assert!(service_shortage_blocks_upgrade(
            ResidenceNeedKind::Church,
            blocked
        ));
    }

    #[test]
    fn continuous_winter_firewood_keeps_calendar_day_thresholds() {
        assert_eq!(service_ticks_per_day(ResidenceNeedKind::Firewood), 600);
        let warning = service_ticks_per_day(ResidenceNeedKind::Firewood)
            * RESIDENCE_SERVICE_WARNING_DAYS as u32;
        let blocked = service_ticks_per_day(ResidenceNeedKind::Firewood)
            * RESIDENCE_UPGRADE_SERVICE_BLOCK_DAYS as u32;

        assert!(!service_shortage_warns(
            ResidenceNeedKind::Firewood,
            warning - 1
        ));
        assert!(service_shortage_warns(
            ResidenceNeedKind::Firewood,
            warning
        ));
        assert!(!service_shortage_blocks_upgrade(
            ResidenceNeedKind::Firewood,
            blocked - 1
        ));
        assert!(service_shortage_blocks_upgrade(
            ResidenceNeedKind::Firewood,
            blocked
        ));
    }

    #[test]
    fn protected_holidays_freeze_daytime_service_and_continuous_heat_clocks() {
        assert!(service_need_clock_active(
            ResidenceNeedKind::Church,
            true,
            false
        ));
        assert!(!service_need_clock_active(
            ResidenceNeedKind::Church,
            false,
            false
        ));
        assert!(service_need_clock_active(
            ResidenceNeedKind::Firewood,
            false,
            false
        ));
        assert!(!service_need_clock_active(
            ResidenceNeedKind::Church,
            true,
            true
        ));
        assert!(!service_need_clock_active(
            ResidenceNeedKind::Firewood,
            true,
            true
        ));
    }

    #[test]
    fn church_standard_scales_with_residence_tier() {
        assert_eq!(required_chapel_tier(1), 1);
        assert_eq!(required_chapel_tier(2), 1);
        assert_eq!(required_chapel_tier(3), 2);
        assert_eq!(required_chapel_tier(4), 3);
    }

    #[test]
    fn only_sustained_tier_four_status_shortages_reduce_optional_spending() {
        let warning = daytime_service_ticks_per_day() * RESIDENCE_SERVICE_WARNING_DAYS as u32;
        assert_eq!(
            tier_four_non_vital_discretionary_multiplier(3, warning),
            1.0
        );
        assert_eq!(
            tier_four_non_vital_discretionary_multiplier(4, warning - 1),
            1.0
        );
        assert_eq!(
            tier_four_non_vital_discretionary_multiplier(4, warning),
            HOUSEHOLD_TIER4_SHORTAGE_DISCRETIONARY_MULTIPLIER,
        );

        let (spendable, units) = scale_discretionary_limits(
            0.1,
            0.48,
            HOUSEHOLD_TIER4_SHORTAGE_DISCRETIONARY_MULTIPLIER,
        );
        assert!((spendable - 0.075).abs() < 1e-9);
        assert!((units - 0.36).abs() < 1e-9);
    }
}
