import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const STAR_SOURCE = 'https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.6.json';
const LINE_SOURCE = 'https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/constellations.lines.json';
const OUTPUT_URL = new URL('../src/sky/celestialCatalog.generated.ts', import.meta.url);

// Classical Western figures inherited from the Greco-Roman/Ptolemaic sky.
// Argo Navis is omitted because the source stores its modern subdivisions;
// far-southern figures that never rise in Gorski Kotar are also unnecessary.
const CLASSICAL_NORTHERN_CONSTELLATIONS = new Set([
  'And', 'Aqr', 'Aql', 'Ari', 'Aur', 'Boo', 'Cnc', 'CMa', 'CMi', 'Cap',
  'Cas', 'Cep', 'Cet', 'CrB', 'Crv', 'Crt', 'Cyg', 'Del', 'Dra', 'Equ',
  'Eri', 'Gem', 'Her', 'Hya', 'Leo', 'Lep', 'Lib', 'Lyr', 'Oph', 'Ori',
  'Peg', 'Per', 'Psc', 'Sge', 'Sgr', 'Sco', 'Ser', 'Tau', 'Tri', 'UMa',
  'UMi', 'Vir',
]);

const [starResponse, lineResponse] = await Promise.all([
  fetch(STAR_SOURCE),
  fetch(LINE_SOURCE),
]);
if (!starResponse.ok || !lineResponse.ok) {
  throw new Error(`Celestial catalog download failed (${starResponse.status}, ${lineResponse.status})`);
}

const stars = await starResponse.json();
const constellations = await lineResponse.json();
const packedStars = stars.features.flatMap((feature) => {
  const [rightAscensionDeg, declinationDeg] = feature.geometry.coordinates;
  const magnitude = Number(feature.properties.mag);
  const colorIndex = Number(feature.properties.bv);
  return [
    rightAscensionDeg,
    declinationDeg,
    magnitude,
    Number.isFinite(colorIndex) ? colorIndex : 0.65,
  ];
});
const packedLines = constellations.features
  .filter((feature) => CLASSICAL_NORTHERN_CONSTELLATIONS.has(feature.id))
  .flatMap((feature) => feature.geometry.coordinates)
  .map((line) => line.flat());

const source = `// Generated by scripts/generateCelestialCatalog.mjs.
// Source: d3-celestial naked-eye star and constellation data, BSD-3-Clause.
// Original coordinates are J2000 equatorial degrees; stars are packed as RA, Dec, magnitude, B-V.
export const NAKED_EYE_STAR_DATA = new Float32Array(${JSON.stringify(packedStars)});

// Each entry is one classical constellation polyline packed as alternating RA/Dec degrees.
export const CLASSICAL_CONSTELLATION_LINES: readonly (readonly number[])[] = ${JSON.stringify(packedLines)};
`;

await writeFile(fileURLToPath(OUTPUT_URL), source);
console.log(
  `Wrote ${packedStars.length / 4} stars and ${packedLines.length} constellation polylines to ${fileURLToPath(OUTPUT_URL)}`,
);
