import { spawnSync } from 'node:child_process';

const tests = [
  'test:rust',
  'test:opening-balance',
  'test:build-menus',
  'test:lodge-logistics',
  'test:industrial-firewood',
  'test:service-territories',
  'test:service-coverage-overlay',
  'test:food-territories',
  'test:institutional-food-reserves',
  'test:granary-fresh-food-target',
  'test:specialty-logistics',
  'test:specialty-trade',
  'test:settlement-specialty-exports',
  'test:backyard-economy-planning',
  'test:household-market-contingency',
  'test:parish-relief-planning',
  'test:textile-economy',
  'test:monastery-hospitality',
  'test:civic-receipts',
  'test:fiscal-policy',
  'test:frontier-security',
  'test:frontier-armory',
  'test:settlement-armament',
  'test:guardhouse-payroll',
  'test:settlement-provisioning',
  'test:settlement-production',
  'test:settlement-geology',
  'test:settlement-prosperity',
  'test:food-preservation',
  'test:settlement-preservation-reserve',
  'test:physical-food-stores',
  'test:physical-bulk-stores',
  'test:physical-armory-stores',
  'test:physical-manure-economy',
  'test:resource-locator',
  'test:whole-resource-units',
  'test:seasonal-producer-stores',
  'test:physical-marketplace-specialties',
  'test:material-economy',
  'test:hydrology',
  'test:civilian-tool-economy',
  'test:village-economy',
  'test:chapel-community',
  'test:chapel-upgrade',
  'test:household-economy',
  'test:residence-upgrade',
  'test:residence-visual-fidelity',
  'test:residence-settlement',
  'test:resident-welfare',
  'test:remedy-logistics',
  'test:settlement-welfare',
  'test:settlement-approval',
  'test:settlement-growth',
  'test:settlement-labor',
  'test:staffing-priority',
  'test:seasonal-labor',
  'test:processor-labor',
  'test:construction-labor',
  'test:labor-steward-forecast',
  'test:year-round-labor',
  'test:worksite-stalls',
  'test:landmark-access',
  'test:economy-parity',
  'test:chapel-parish',
  'test:marketplace-gating',
  'test:marketplace-trade',
  'test:settlement-schedule',
  'test:seasons',
  'test:weather-visuals',
  'test:day-night',
  'test:naive-art-post',
  'test:post-processing-pipeline',
  'test:celestial-sky',
  'test:fires',
  'test:fire-safety-planning',
  'test:fire-recovery-planning',
  'test:world-config',
  'test:world-terrain-presets',
  'test:regional-resources',
  'test:startup-chunking',
  'test:visual-performance-hooks',
  'test:renderer-frame-stats',
  'test:connection-recovery',
  'test:tutorial-progress',
  'test:building-processor-status',
  'test:industrial-water-logistics',
  'test:chapel-bell-schedule',
  'test:expanded-settlement',
  'test:farming',
  'test:farm-field-visuals',
  'test:grain-logistics',
  'test:monastery-polish',
  'test:backyard-gardens',
  'test:residence-terrain',
  'test:building-art',
  'test:static-fixture-batch',
  'test:static-shadow-batch',
  'test:building-shadow-batch',
  'test:hamlet-fixture',
  'test:hamlet-forest-edge-layer',
  'test:hamlet-under-canopy-ground',
  'test:visual-gauntlet-archive',
  'test:visual-gauntlet-evidence',
  'test:visual-gauntlet-round-48-contract',
  'test:visual-gauntlet-round-52-contract',
  'test:visual-gauntlet-round-54-contract',
  'test:visual-gauntlet-round-55-contract',
  'test:visual-gauntlet-round-56-contract',
  'test:visual-gauntlet-round-57-contract',
  'test:camera-controller',
  'test:first-person-mode',
  'test:world-map',
  'test:first-person-collision',
  'test:first-person-collision-performance',
  'test:client-sync',
  'test:placement-regressions',
  'test:road-building-connections',
  'test:road-junction-topology',
  'test:road-rock-clearance',
  'test:deer-wildlife',
  'test:livestock',
  'test:livestock-policy',
  'test:agent-visuals',
  'test:ambient-behaviors',
  'test:worker-agents',
  'test:agent-navigation-performance',
  'test:crowd-renderer-pacing',
  'test:crowd-source-model-batching',
  'test:shadow-bounds-pacing',
  'test:presentation-hot-path-pacing',
  'test:building-static-batching',
  'test:residence-static-batching',
  'test:household-routines',
  'test:civic-logistics',
  'test:storehouse-stock-targets',
  'test:processor-output-targets',
  'test:construction-logistics',
  'test:founding-site',
  'test:starter-camp',
  'test:demolition-reclamation',
  'test:delivery-pacing',
  'test:delivery-target-selection',
  'test:quarry-balance',
  'test:rich-stone',
  'test:rich-clay',
  'test:mineral-deposits',
  'test:fishing',
  'test:foraging-ecology',
  'test:river-simulation',
  'test:river-water-material',
  'test:seedthree-forest-ecology',
  'test:seedthree-forest-compaction',
  'test:seedthree-overview-billboard-fade',
  'test:forest-startup-streaming',
  'test:vegetation-startup-performance',
  'test:seedthree-winter-foliage',
  'test:seedthree-cattail-heights',
  'test:close-ground-vegetation',
  'test:terrain-ecology-material',
] as const;

let failed = 0;

for (const script of tests) {
  console.log(`\n==> npm run ${script}`);
  const result = spawnSync(`npm run ${script}`, {
    stdio: 'inherit',
    shell: true,
    env: process.env,
  });
  if (result.status !== 0) {
    failed += 1;
    console.error(`FAILED: ${script}`);
  }
}

if (failed > 0) {
  console.error(`\n${failed} test suite(s) failed.`);
  process.exit(1);
}

console.log(`\nAll ${tests.length} test suites passed.`);
