import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as THREE from 'three';
import { BUILDING_COSTS, BUILDING_STORAGE_CAPS, MASON_STONE_PER_CYCLE, MASON_DRESSED_STONE_PER_CYCLE } from '../src/generated/gameBalance.ts';
import { createBuildingMesh } from '../src/buildings/BuildingMeshes.ts';
import { createStoneMasonMesh } from '../src/buildings/meshes/stoneMasonMesh.ts';
import { getBuildingFootprintHalfExtents } from '../src/buildings/BuildingFootprint.ts';
import { syncBulkStockpileVisuals, bulkStockpileVisualSignature } from '../src/buildings/bulkStockpileVisuals.ts';
import { constructionLaborReady } from '../src/economy/constructionLabor.ts';
import { computeSettlementConstructionPlan } from '../src/economy/settlementConstruction.ts';
import { chapelUpgradeCost } from '../src/economy/chapelUpgrade.ts';
import { fireRecoveryCost } from '../src/fires/fireRecovery.ts';
import { buildingStoredResourceTotal, buildingSharedStorageRoom } from '../src/economy/sharedStorageCapacity.ts';
import { processorOutputHeadroom } from '../src/economy/processorOutputPolicy.ts';
import { selectDirectProcessorInputTarget, localMaterialInputCommodities, directlyDispatchedProcessorInputPerCycle } from '../src/logistics/processorInputLogistics.ts';
import { STORAGE_COMMODITY_CODES, storageAcceptsCommodity } from '../src/economy/storageAcceptancePolicy.ts';
import { RESOURCE_COST_KINDS, renderResourceCost } from '../src/ui/resourceCost.ts';
import { HUD_CONSTRUCTION_RESOURCE_KINDS } from '../src/ui/hudResourceCards.ts';
import type { BuildingState } from '../src/resources/types.ts';

assert.equal(MASON_STONE_PER_CYCLE, 2 * MASON_DRESSED_STONE_PER_CYCLE);
assert(!BUILDING_COSTS.stone_mason.dressedStone, 'production chain can bootstrap');
assert(!chapelUpgradeCost(1)!.dressedStone, 'small fieldstone church remains accessible');
assert.equal(chapelUpgradeCost(2)!.dressedStone, 64);
assert.equal(chapelUpgradeCost(3)!.dressedStone, 240);
assert(BUILDING_COSTS.monastery.dressedStone! > 0 && BUILDING_COSTS.town_hall.dressedStone! > 0);
assert.equal(STORAGE_COMMODITY_CODES.dressedStone, 76);
const yard={id:'yard',kind:'stone_mason',assignedLabor:2,constructionComplete:true,stone:0,dressedStone:0,water:0,timber:0,firewood:0,ironwork:0} as BuildingState;
const store={...yard,id:'store',kind:'village_storehouse'} as BuildingState;
assert(storageAcceptsCommodity(store,'dressedStone'));
assert(BUILDING_STORAGE_CAPS.village_storehouse.dressedStone! > 0);
assert.equal(directlyDispatchedProcessorInputPerCycle('stone_mason','stone'),8);
assert(localMaterialInputCommodities('large_quarry',{stone:10}).includes('stone'));
assert(localMaterialInputCommodities('stone_mason',{dressedStone:10}).includes('dressedStone'));
const inbound=selectDirectProcessorInputTarget([yard], 'quarry', 'stone',()=>12);
assert.equal(inbound?.target.id,'yard');
assert.equal(inbound?.desiredStock,24,'staffed yard stages three complete cycles');
const outbound=selectDirectProcessorInputTarget([store], 'yard', 'dressedStone',()=>14);
assert.equal(outbound?.target.id,'store');
assert.equal(selectDirectProcessorInputTarget([yard],'quarry','stone',()=>null),null);
assert.equal(processorOutputHeadroom({...yard,dressedStone:64}),0);
assert.equal(buildingStoredResourceTotal({...yard,stone:96,dressedStone:64}),160);
assert.equal(buildingSharedStorageRoom({...yard,stone:96,dressedStone:64}),0);
const site={...yard,id:'site',kind:'town_hall',constructionComplete:false,constructionPriority:2,constructionProgress:.5,constructionRequiredTimber:0,constructionRequiredStone:0,constructionRequiredIronwork:0,constructionRequiredRoofTiles:0,constructionRequiredDressedStone:10,constructionDeliveredDressedStone:0,constructionReservedDressedStone:10} as BuildingState;
assert.equal(constructionLaborReady(site),false,'missing blocks stop builders');
assert.equal(constructionLaborReady({...site,constructionDeliveredDressedStone:10}),true);
const plan=computeSettlementConstructionPlan({state:{buildings:new Map([['site',site]]),deliveryTrips:new Map()},roadComponentFor:()=>1,hasRoadAccess:()=>true} as never);
assert.equal(plan.materials.dressedStone.required,10);
assert.equal(plan.materials.roofTiles.required,0,'block claims cannot become tile claims');
const repair=fireRecoveryCost({timber:0,stone:0,dressedStone:40},1,true,false);
assert(repair.dressedStone! > 0);
assert(RESOURCE_COST_KINDS.includes('dressedStone') && HUD_CONSTRUCTION_RESOURCE_KINDS.includes('dressedStone'));
assert.match(renderResourceCost({timber:0,stone:0,dressedStone:5}),/dressedStone/);
const root=createBuildingMesh('stone_mason');
const plot=getBuildingFootprintHalfExtents('stone_mason');
const model=createStoneMasonMesh();
const bounds=new THREE.Box3().setFromObject(model);
assert(bounds.min.x >= -plot.halfWidth && bounds.max.x <= plot.halfWidth);
assert(bounds.min.z >= -plot.halfDepth && bounds.max.z <= plot.halfDepth);
assert(root.userData.proceduralArchitectureMetrics.withinVisibleTriangleCeiling);
assert(root.getObjectByName('MasonDressedStoneStock0'),'compiled stock slot survives');
syncBulkStockpileVisuals(root,{...yard,stone:96,dressedStone:64});
assert(root.getObjectByName('MasonDressedStoneStock7')?.visible);
syncBulkStockpileVisuals(root,yard);
assert.equal(root.getObjectByName('MasonDressedStoneStock0')?.visible,false);
assert.notEqual(bulkStockpileVisualSignature(yard),bulkStockpileVisualSignature({...yard,dressedStone:64}));
for(const p of ['public/assets/ui/build-menu/cards/stone-mason.webp','public/assets/ui/icons/materials/dressed-stone.svg'])assert(readFileSync(p).length>300);
console.log('Dressed stone: production routing, finite storage, construction readiness, cost separation, repairs, HUD, compiled mesh, footprint, and live stock slots passed.');
